// Regenerates src/script/physics/fm3/reference/f16Tables.ts from the F-16
// aerodynamics that shipped with the removed JSBSim model.
//
// The tables are the Stevens & Lewis F-16 data set (angle of attack −10..45°),
// itself a subset of NASA TP-1538's wind-tunnel data. JSBSim left the repo in
// commit 3c4642a, so the XML is read from the commit before it:
//
//     node tools/fm3/extract_f16_reference.mjs
//
// Every coefficient keeps the exact list of JSBSim properties it is multiplied
// by, so a reader can tell "per radian of sideslip" from "per unit of c/2V·q"
// without guessing.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const SOURCE_REV = '3c4642a^';
const SOURCE_PATH = 'assets/jsbsim/aircraft/f16/f16.xml';
const OUT = path.join('src', 'script', 'physics', 'fm3', 'reference', 'f16Tables.ts');

const xml = execFileSync('git', ['show', `${SOURCE_REV}:${SOURCE_PATH}`], { encoding: 'utf8', maxBuffer: 16 << 20 });

const numbers = text => text.trim().split(/\s+/).filter(Boolean).map(Number);

const tables = {};
const functionRe = /<function name="aero\/coefficient\/([^"]+)">([\s\S]*?)<\/function>/g;
let m;
while ((m = functionRe.exec(xml)) !== null) {
    const [, name, body] = m;
    const description = (body.match(/<description>([^<]*)<\/description>/) ?? [])[1] ?? '';
    const tableStart = body.indexOf('<table');
    const head = tableStart >= 0 ? body.slice(0, tableStart) : body;
    const factors = [...head.matchAll(/<property>([^<]+)<\/property>/g)].map(x => x[1].trim());
    const valueMatch = head.match(/<value>([^<]+)<\/value>/);
    const entry = { description, factors };
    if (valueMatch) entry.value = Number(valueMatch[1]);

    if (tableStart >= 0) {
        const table = body.slice(tableStart);
        const vars = [...table.matchAll(/<independentVar(?:\s+lookup="(row|column)")?>([^<]+)<\/independentVar>/g)]
            .map(x => ({ lookup: x[1] ?? 'row', property: x[2].trim() }));
        const data = (table.match(/<tableData>([\s\S]*?)<\/tableData>/) ?? [])[1];
        const lines = data.trim().split('\n').map(l => numbers(l)).filter(l => l.length > 0);
        if (vars.length === 1) {
            entry.row = vars[0].property;
            entry.rows = lines.map(l => l[0]);
            entry.data = lines.map(l => l[1]);
        } else {
            entry.row = vars.find(v => v.lookup === 'row').property;
            entry.column = vars.find(v => v.lookup === 'column').property;
            entry.columns = lines[0];
            entry.rows = lines.slice(1).map(l => l[0]);
            entry.data = lines.slice(1).map(l => l.slice(1));
            for (const row of entry.data) {
                if (row.length !== entry.columns.length) throw new Error(`${name}: ragged table`);
            }
        }
    }
    tables[name] = entry;
}

const metric = tag => {
    const mm = xml.match(new RegExp(`<${tag} unit="([^"]+)">\\s*([^<]+)</${tag}>`));
    return mm ? { unit: mm[1], value: Number(mm[2]) } : undefined;
};

const header = `/**
 * F-16 aerodynamic coefficient tables, for validating FM3 — never for flying it.
 *
 * GENERATED by tools/fm3/extract_f16_reference.mjs from ${SOURCE_PATH} at
 * ${SOURCE_REV} (the JSBSim F-16, removed from the repo in 3c4642a). Do not edit.
 *
 * The data set is Stevens & Lewis's F-16 model, derived from the wind-tunnel data
 * of NASA TP-1538 (Nguyen et al., 1979): angle of attack −10..45°, sideslip ±30°,
 * low speed. Each entry lists the JSBSim properties its value is multiplied by
 * (\`factors\`), which fixes its units: e.g. \`aero/ci2vel\` × \`velocities/q-aero-rad_sec\`
 * means "per unit of q·c̄/2V". Angles are radians; forces are in wind axes (LIFT,
 * DRAG, SIDE) and moments about the aerodynamic reference point (0.35 c̄).
 * JSBSim's elevator is positive trailing-edge down.
 */

export interface F16Table {
    description: string;
    factors: string[];
    value?: number;
    row?: string;
    column?: string;
    rows?: number[];
    columns?: number[];
    data?: number[] | number[][];
}

export const F16_METRICS = ${JSON.stringify({
    wingAreaFt2: metric('wingarea')?.value,
    wingSpanFt: metric('wingspan')?.value,
    chordFt: metric('chord')?.value,
    htailAreaFt2: metric('htailarea')?.value,
    htailArmFt: metric('htailarm')?.value,
    vtailAreaFt2: metric('vtailarea')?.value,
}, null, 4)} as const;

export const F16_TABLES: Record<string, F16Table> = ${JSON.stringify(tables, null, 4)};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header);
console.log(`wrote ${OUT}: ${Object.keys(tables).length} coefficients`);
for (const [name, t] of Object.entries(tables)) {
    const shape = t.columns ? `${t.rows.length}x${t.columns.length}` : t.rows ? `${t.rows.length}` : 'const';
    console.log(`  ${name.padEnd(12)} ${shape.padEnd(6)} × ${t.factors.join(' · ')}${t.value !== undefined ? ` = ${t.value}` : ''}${t.column ? ` [${t.row} × ${t.column}]` : t.row ? ` [${t.row}]` : ''}`);
}
