/**
 * F-16 aerodynamic coefficient tables, for validating FM3 — never for flying it.
 *
 * GENERATED by tools/fm3/extract_f16_reference.mjs from assets/jsbsim/aircraft/f16/f16.xml at
 * 3c4642a^ (the JSBSim F-16, removed from the repo in 3c4642a). Do not edit.
 *
 * The data set is Stevens & Lewis's F-16 model, derived from the wind-tunnel data
 * of NASA TP-1538 (Nguyen et al., 1979): angle of attack −10..45°, sideslip ±30°,
 * low speed. Each entry lists the JSBSim properties its value is multiplied by
 * (`factors`), which fixes its units: e.g. `aero/ci2vel` × `velocities/q-aero-rad_sec`
 * means "per unit of q·c̄/2V". Angles are radians; forces are in wind axes (LIFT,
 * DRAG, SIDE) and moments about the aerodynamic reference point (0.35 c̄).
 * JSBSim's elevator is positive trailing-edge down.
 */

export interface F16Table {
    description: string;
    factors: string[];
    value?: number;
    row?: string;
    column?: string;
    rows?: number[];
    columns?: number[];
    data?: number[] | number[][];
}

export const F16_METRICS = {
    "wingAreaFt2": 300,
    "wingSpanFt": 30,
    "chordFt": 11.32,
    "htailAreaFt2": 63.7,
    "htailArmFt": 16.46,
    "vtailAreaFt2": 54.75
} as const;

export const F16_TABLES: Record<string, F16Table> = {
    "CDDh": {
        "description": "Drag_due_to_horizontal_tail_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft"
        ],
        "row": "aero/alpha-rad",
        "column": "fcs/elevator-pos-rad",
        "columns": [
            -0.436,
            -0.218,
            0,
            0.218,
            0.436
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                0.217,
                0.174,
                0.156,
                0.181,
                0.23
            ],
            [
                0.094,
                0.055,
                0.041,
                0.062,
                0.101
            ],
            [
                0.081,
                0.04,
                0.021,
                0.039,
                0.076
            ],
            [
                0.106,
                0.061,
                0.04,
                0.057,
                0.101
            ],
            [
                0.166,
                0.119,
                0.096,
                0.114,
                0.158
            ],
            [
                0.252,
                0.203,
                0.182,
                0.202,
                0.24
            ],
            [
                0.404,
                0.362,
                0.347,
                0.371,
                0.416
            ],
            [
                0.628,
                0.588,
                0.577,
                0.601,
                0.637
            ],
            [
                0.875,
                0.84,
                0.826,
                0.852,
                0.88
            ],
            [
                1.127,
                1.095,
                1.084,
                1.102,
                1.125
            ],
            [
                1.365,
                1.334,
                1.326,
                1.338,
                1.356
            ],
            [
                1.517,
                1.487,
                1.478,
                1.482,
                1.489
            ]
        ]
    },
    "CDmach": {
        "description": "Drag_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft"
        ],
        "row": "velocities/mach",
        "rows": [
            0,
            0.81,
            1.1,
            1.8
        ],
        "data": [
            0,
            0,
            0.023,
            0.015
        ]
    },
    "CDDlef": {
        "description": "Drag_due_to_leading_edge_flap_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/lef-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            0.003,
            0.001,
            0,
            0.001,
            0.002,
            0.004,
            0.007,
            0.011,
            0.015,
            0.019,
            0.023,
            0.024
        ]
    },
    "CDDflaps": {
        "description": "Drag_due_to_trailing_edge_flaps",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/flaperon-mix-rad"
        ],
        "value": 0.08
    },
    "CDgear": {
        "description": "Drag_due_to_gear",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "gear/gear-pos-norm"
        ],
        "value": 0.027
    },
    "CDDsb": {
        "description": "Drag_due_to_speedbrake_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/speedbrake-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.0545,
            -0.0225,
            0.0096,
            0.059,
            0.1244,
            0.2182,
            0.2324,
            0.2029,
            0.1435,
            0.1046,
            0.1363,
            0.1196
        ]
    },
    "CDq": {
        "description": "Drag_due_to_pitch_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "velocities/q-aero-rad_sec",
            "aero/ci2vel"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -1.265,
            -2.139,
            -0.308,
            1.402,
            3.369,
            5.135,
            6.88,
            10.06,
            13.201,
            15.872,
            23.217,
            24.105
        ]
    },
    "CDq_Dlef": {
        "description": "Drag_due_to_pitch_rate_and_leading_edge_flap_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "velocities/q-aero-rad_sec",
            "aero/ci2vel",
            "fcs/lef-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            0.067,
            0.034,
            0.028,
            0.029,
            0.033,
            0.059,
            0.061,
            0.027,
            0.036,
            0.047,
            0.029,
            0.015
        ]
    },
    "CYb": {
        "description": "Side_force_due_to_beta",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "aero/beta-rad"
        ],
        "value": -1.146
    },
    "CYb_M": {
        "description": "Change_in_Side_force_due_to_beta_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "aero/beta-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.4,
            1.2,
            1.6
        ],
        "data": [
            0,
            0.0573,
            -0.1719
        ]
    },
    "CYDa": {
        "description": "Side_force_due_to_aileron",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/aileron-pos-rad"
        ],
        "value": -0.0226
    },
    "CYdr": {
        "description": "Side_force_due_to_rudder",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/rudder-pos-rad"
        ],
        "value": 0.086
    },
    "CYp": {
        "description": "Side_force_due_to_roll_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "aero/bi2vel",
            "velocities/p-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.108,
            -0.108,
            -0.188,
            0.11,
            0.258,
            0.226,
            0.344,
            0.362,
            0.611,
            0.529,
            0.298,
            -0.227
        ]
    },
    "CYr": {
        "description": "Side_force_due_to_yaw_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "aero/bi2vel",
            "velocities/r-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            0.882,
            0.852,
            0.876,
            0.958,
            0.962,
            0.974,
            0.819,
            0.483,
            0.59,
            1.21,
            -0.493,
            -1.04
        ]
    },
    "CLDh": {
        "description": "Lift_due_to_horizontal_tail_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "aero/function/kCLge"
        ],
        "row": "aero/alpha-rad",
        "column": "fcs/elevator-pos-rad",
        "columns": [
            -0.436,
            -0.218,
            0,
            0.218,
            0.436
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                -0.659,
                -0.709,
                -0.754,
                -0.792,
                -0.825
            ],
            [
                -0.151,
                -0.196,
                -0.238,
                -0.278,
                -0.316
            ],
            [
                0.183,
                0.141,
                0.1,
                0.059,
                0.017
            ],
            [
                0.491,
                0.454,
                0.414,
                0.371,
                0.326
            ],
            [
                0.797,
                0.763,
                0.725,
                0.68,
                0.63
            ],
            [
                1.108,
                1.079,
                1.041,
                0.993,
                0.94
            ],
            [
                1.395,
                1.366,
                1.327,
                1.274,
                1.214
            ],
            [
                1.615,
                1.587,
                1.547,
                1.49,
                1.427
            ],
            [
                1.804,
                1.777,
                1.737,
                1.674,
                1.61
            ],
            [
                1.9,
                1.872,
                1.829,
                1.766,
                1.699
            ],
            [
                1.898,
                1.869,
                1.822,
                1.757,
                1.689
            ],
            [
                1.753,
                1.724,
                1.674,
                1.612,
                1.546
            ]
        ]
    },
    "CLDlef": {
        "description": "Lift_due_to_leading_edge_flap_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/lef-pos-rad",
            "aero/function/kCLge"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.012,
            -0.004,
            0.002,
            0.007,
            0.012,
            0.018,
            0.022,
            0.025,
            0.026,
            0.028,
            0.028,
            0.025
        ]
    },
    "CLDflaps": {
        "description": "Delta_Lift_due_to_trailing_edge_flaps",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "fcs/flaperon-mix-rad",
            "aero/function/kCLge"
        ],
        "value": 0.35
    },
    "CLDsb": {
        "description": "Lift_due_to_speedbrake_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "aero/function/kCLge",
            "fcs/speedbrake-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            0.3645,
            0.3678,
            0.3684,
            0.2522,
            0.271,
            0.3615,
            0.1283,
            0.0075,
            -0.1311,
            -0.1836,
            -0.1161,
            -0.1064
        ]
    },
    "CLq": {
        "description": "Lift_due_to_pitch_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "velocities/q-aero-rad_sec",
            "aero/function/kCLge",
            "aero/ci2vel"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            8.7127,
            25.7114,
            28.9,
            31.3973,
            31.0872,
            30.4071,
            26.9735,
            26.4242,
            25.8647,
            25.2654,
            30.5158,
            25.8165
        ]
    },
    "CLq_Dsb": {
        "description": "Lift_due_to_pitch_rate_and_speedbrake_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "velocities/q-aero-rad_sec",
            "aero/ci2vel",
            "fcs/speedbrake-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.256,
            -0.062,
            -0.01,
            0.02,
            -0.011,
            0.053,
            0.063,
            -0.009,
            0.034,
            0.042,
            0.005,
            0.001
        ]
    },
    "Clb": {
        "description": "Roll_moment_due_to_beta",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft"
        ],
        "row": "aero/alpha-rad",
        "column": "aero/beta-rad",
        "columns": [
            -0.524,
            -0.436,
            -0.349,
            -0.262,
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                -0.009,
                -0.007,
                0,
                0.001,
                0.003,
                0.001,
                0,
                -0.001,
                -0.003,
                -0.001,
                0,
                0.007,
                0.009
            ],
            [
                0.011,
                0.01,
                0.01,
                0.01,
                0.009,
                0.004,
                0,
                -0.004,
                -0.009,
                -0.01,
                -0.01,
                -0.01,
                -0.011
            ],
            [
                0.023,
                0.023,
                0.022,
                0.02,
                0.017,
                0.008,
                0,
                -0.008,
                -0.017,
                -0.02,
                -0.022,
                -0.023,
                -0.023
            ],
            [
                0.037,
                0.034,
                0.034,
                0.03,
                0.024,
                0.012,
                0,
                -0.012,
                -0.024,
                -0.03,
                -0.034,
                -0.034,
                -0.037
            ],
            [
                0.05,
                0.049,
                0.047,
                0.039,
                0.03,
                0.016,
                0,
                -0.016,
                -0.03,
                -0.039,
                -0.047,
                -0.049,
                -0.05
            ],
            [
                0.068,
                0.063,
                0.06,
                0.054,
                0.041,
                0.022,
                0,
                -0.022,
                -0.041,
                -0.054,
                -0.06,
                -0.063,
                -0.068
            ],
            [
                0.089,
                0.081,
                0.069,
                0.057,
                0.045,
                0.022,
                0,
                -0.022,
                -0.045,
                -0.057,
                -0.069,
                -0.081,
                -0.089
            ],
            [
                0.088,
                0.079,
                0.067,
                0.054,
                0.04,
                0.021,
                0,
                -0.021,
                -0.04,
                -0.054,
                -0.067,
                -0.079,
                -0.088
            ],
            [
                0.091,
                0.06,
                0.033,
                0.023,
                0.016,
                0.015,
                0,
                -0.015,
                -0.016,
                -0.023,
                -0.033,
                -0.06,
                -0.091
            ],
            [
                0.076,
                0.058,
                0.036,
                0.006,
                0.002,
                0.008,
                0,
                -0.008,
                -0.002,
                -0.006,
                -0.036,
                -0.058,
                -0.076
            ],
            [
                0.077,
                0.062,
                0.035,
                0.014,
                0.01,
                0.013,
                0,
                -0.013,
                -0.01,
                -0.014,
                -0.035,
                -0.062,
                -0.077
            ],
            [
                0.076,
                0.059,
                0.035,
                0.027,
                0.019,
                0.015,
                0,
                -0.015,
                -0.019,
                -0.027,
                -0.035,
                -0.059,
                -0.076
            ]
        ]
    },
    "Clb_M": {
        "description": "Change_in_Roll_moment_due_to_beta_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/beta-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            0.8,
            1,
            1.2,
            1.4,
            1.6
        ],
        "data": [
            0,
            0.1891,
            0.1776,
            0.1375,
            0.1203,
            0.0859
        ]
    },
    "Clp": {
        "description": "Roll_moment_due_to_roll_rate_(roll_damping)",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/bi2vel",
            "velocities/p-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.36,
            -0.359,
            -0.443,
            -0.42,
            -0.383,
            -0.375,
            -0.329,
            -0.294,
            -0.23,
            -0.21,
            -0.12,
            -0.1
        ]
    },
    "Clr": {
        "description": "Roll_moment_due_to_yaw_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/bi2vel",
            "velocities/r-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.126,
            -0.026,
            0.063,
            0.113,
            0.208,
            0.23,
            0.319,
            0.437,
            0.68,
            0.1,
            0.447,
            -0.33
        ]
    },
    "Clda": {
        "description": "Roll_moment_due_to_aileron",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "fcs/aileron-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "column": "aero/beta-rad",
        "columns": [
            -0.524,
            -0.349,
            -0.175,
            0,
            0.175,
            0.349,
            0.524
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                0.041,
                0.041,
                0.042,
                0.04,
                0.043,
                0.044,
                0.043
            ],
            [
                0.052,
                0.053,
                0.053,
                0.052,
                0.049,
                0.048,
                0.049
            ],
            [
                0.053,
                0.053,
                0.052,
                0.051,
                0.048,
                0.048,
                0.047
            ],
            [
                0.056,
                0.053,
                0.051,
                0.052,
                0.049,
                0.047,
                0.045
            ],
            [
                0.05,
                0.05,
                0.049,
                0.048,
                0.043,
                0.042,
                0.042
            ],
            [
                0.056,
                0.051,
                0.049,
                0.048,
                0.042,
                0.041,
                0.037
            ],
            [
                0.082,
                0.066,
                0.043,
                0.042,
                0.042,
                0.02,
                0.003
            ],
            [
                0.059,
                0.043,
                0.035,
                0.037,
                0.036,
                0.028,
                0.013
            ],
            [
                0.042,
                0.038,
                0.026,
                0.031,
                0.025,
                0.013,
                0.01
            ],
            [
                0.038,
                0.027,
                0.016,
                0.026,
                0.021,
                0.014,
                0.003
            ],
            [
                0.027,
                0.023,
                0.018,
                0.017,
                0.016,
                0.011,
                0.007
            ],
            [
                0.017,
                0.016,
                0.014,
                0.012,
                0.011,
                -0.01,
                0.008
            ]
        ]
    },
    "Clda_M": {
        "description": "Change_in_Roll_moment_due_to_aileron_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/alpha-rad",
            "fcs/aileron-pos-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            1.2,
            1.6
        ],
        "data": [
            0,
            -0.063,
            -0.063
        ]
    },
    "Cldr_M": {
        "description": "Change_in_Roll_moment_due_to_rudder_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/alpha-rad",
            "fcs/rudder-pos-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            1.6
        ],
        "data": [
            0,
            -0.0201
        ]
    },
    "Cldr": {
        "description": "Roll_moment_due_to_rudder",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "fcs/rudder-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "column": "aero/beta-rad",
        "columns": [
            -0.524,
            -0.349,
            -0.175,
            0,
            0.175,
            0.349,
            0.524
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                0.005,
                0.007,
                0.013,
                0.018,
                0.015,
                0.021,
                0.023
            ],
            [
                0.017,
                0.016,
                0.013,
                0.015,
                0.014,
                0.011,
                0.01
            ],
            [
                0.014,
                0.014,
                0.011,
                0.015,
                0.013,
                0.01,
                0.011
            ],
            [
                0.01,
                0.014,
                0.012,
                0.014,
                0.013,
                0.011,
                0.011
            ],
            [
                -0.005,
                0.013,
                0.011,
                0.014,
                0.012,
                0.01,
                0.011
            ],
            [
                0.009,
                0.009,
                0.009,
                0.014,
                0.011,
                0.009,
                0.01
            ],
            [
                0.019,
                0.012,
                0.008,
                0.014,
                0.011,
                0.008,
                0.008
            ],
            [
                0.005,
                0.005,
                0.005,
                0.015,
                0.01,
                0.01,
                0.01
            ],
            [
                0,
                0,
                0,
                0.013,
                0.008,
                0.006,
                0.006
            ],
            [
                -0.005,
                0.004,
                0.005,
                0.011,
                0.008,
                0.005,
                0.014
            ],
            [
                -0.011,
                0.009,
                0.003,
                0.006,
                0.007,
                0,
                0.02
            ],
            [
                0.008,
                0.007,
                0.005,
                0.001,
                0.003,
                0.001,
                0
            ]
        ]
    },
    "CmDh": {
        "description": "Pitch_moment_due_to_horizontal_tail_deflection",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/cbarw-ft"
        ],
        "row": "aero/alpha-rad",
        "column": "fcs/elevator-pos-rad",
        "columns": [
            -0.436,
            -0.218,
            0,
            0.218,
            0.436
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                0.205,
                0.081,
                -0.046,
                -0.174,
                -0.259
            ],
            [
                0.168,
                0.077,
                -0.02,
                -0.145,
                -0.202
            ],
            [
                0.186,
                0.107,
                -0.009,
                -0.121,
                -0.184
            ],
            [
                0.196,
                0.11,
                -0.005,
                -0.127,
                -0.193
            ],
            [
                0.213,
                0.11,
                -0.006,
                -0.129,
                -0.199
            ],
            [
                0.251,
                0.141,
                0.01,
                -0.102,
                -0.15
            ],
            [
                0.245,
                0.127,
                0.006,
                -0.097,
                -0.16
            ],
            [
                0.238,
                0.119,
                -0.001,
                -0.113,
                -0.167
            ],
            [
                0.252,
                0.133,
                0.014,
                -0.087,
                -0.104
            ],
            [
                0.231,
                0.108,
                0,
                -0.084,
                -0.076
            ],
            [
                0.198,
                0.081,
                -0.013,
                -0.069,
                -0.041
            ],
            [
                0.192,
                0.093,
                0.032,
                -0.006,
                -0.005
            ]
        ]
    },
    "Cma_M": {
        "description": "Change_in_Pitch_moment_due_to_alpha_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/cbarw-ft",
            "aero/alpha-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            0.8,
            0.9,
            1,
            1.1,
            1.2
        ],
        "data": [
            0,
            0.0974,
            -0.3323,
            -0.9626,
            -0.848,
            -0.7907
        ]
    },
    "CmDsb": {
        "description": "Change_in_Pitch_moment_due_to_speedbrake",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/cbarw-ft",
            "fcs/speedbrake-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.0036,
            -0.0036,
            -0.0036,
            0.0303,
            0.0225,
            0.0128,
            0.0252,
            0.0275,
            -0.0171,
            -0.0448,
            -0.0737,
            -0.0884
        ]
    },
    "Cmq": {
        "description": "Pitch_moment_due_to_pitch_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/cbarw-ft",
            "aero/ci2vel",
            "velocities/q-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -7.21,
            -5.4,
            -5.23,
            -5.26,
            -6.11,
            -6.64,
            -5.69,
            -6,
            -6.2,
            -6.4,
            -6.6,
            -6
        ]
    },
    "Cnb": {
        "description": "Yaw_moment_due_to_beta",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft"
        ],
        "row": "aero/alpha-rad",
        "column": "aero/beta-rad",
        "columns": [
            -0.524,
            -0.436,
            -0.349,
            -0.262,
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                -0.079,
                -0.074,
                -0.064,
                -0.056,
                -0.038,
                -0.018,
                0,
                0.018,
                0.038,
                0.056,
                0.064,
                0.074,
                0.079
            ],
            [
                -0.09,
                -0.086,
                -0.077,
                -0.057,
                -0.042,
                -0.019,
                0,
                0.019,
                0.042,
                0.057,
                0.077,
                0.086,
                0.09
            ],
            [
                -0.106,
                -0.093,
                -0.076,
                -0.059,
                -0.042,
                -0.018,
                0,
                0.018,
                0.042,
                0.059,
                0.076,
                0.093,
                0.106
            ],
            [
                -0.106,
                -0.089,
                -0.074,
                -0.058,
                -0.042,
                -0.019,
                0,
                0.019,
                0.042,
                0.058,
                0.074,
                0.089,
                0.106
            ],
            [
                -0.096,
                -0.08,
                -0.073,
                -0.058,
                -0.043,
                -0.019,
                0,
                0.019,
                0.043,
                0.058,
                0.073,
                0.08,
                0.096
            ],
            [
                -0.08,
                -0.062,
                -0.057,
                -0.053,
                -0.039,
                -0.018,
                0,
                0.018,
                0.039,
                0.053,
                0.057,
                0.062,
                0.08
            ],
            [
                -0.068,
                -0.049,
                -0.029,
                -0.032,
                -0.03,
                -0.013,
                0,
                0.013,
                0.03,
                0.032,
                0.029,
                0.049,
                0.068
            ],
            [
                -0.03,
                -0.022,
                -0.007,
                -0.012,
                -0.017,
                -0.007,
                0,
                0.007,
                0.017,
                0.012,
                0.007,
                0.022,
                0.03
            ],
            [
                -0.064,
                -0.028,
                -0.012,
                -0.002,
                -0.004,
                -0.004,
                0,
                0.004,
                0.004,
                0.002,
                0.012,
                0.028,
                0.064
            ],
            [
                -0.015,
                0.012,
                0.034,
                0.046,
                0.035,
                0.014,
                0,
                -0.014,
                -0.035,
                -0.046,
                -0.034,
                -0.012,
                0.015
            ],
            [
                -0.011,
                0.002,
                0.065,
                0.071,
                0.047,
                0.017,
                0,
                -0.017,
                -0.047,
                -0.071,
                -0.065,
                -0.002,
                0.011
            ],
            [
                0.001,
                0.013,
                0.041,
                0.073,
                0.057,
                0.033,
                0,
                -0.033,
                -0.057,
                -0.073,
                -0.041,
                -0.013,
                -0.001
            ]
        ]
    },
    "Cnb_M": {
        "description": "Change_in_Yaw_moment_due_to_beta_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/beta-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            0.7,
            0.8,
            0.9,
            1,
            1.2,
            1.4,
            1.6
        ],
        "data": [
            0,
            -0.0688,
            -0.0172,
            0.0229,
            0,
            -0.0688,
            0.0057,
            0.0688
        ]
    },
    "Cnp": {
        "description": "Yaw_moment_due_to_roll_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/bi2vel",
            "velocities/p-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.061,
            -0.052,
            -0.052,
            0.012,
            0.013,
            0.024,
            -0.05,
            -0.15,
            -0.13,
            -0.158,
            -0.24,
            -0.15
        ]
    },
    "Cnr": {
        "description": "Yaw_moment_due_to_yaw_rate",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/bi2vel",
            "velocities/r-aero-rad_sec"
        ],
        "row": "aero/alpha-rad",
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            -0.38,
            -0.363,
            -0.378,
            -0.386,
            -0.37,
            -0.453,
            -0.55,
            -0.582,
            -0.595,
            -0.637,
            -1.02,
            -0.84
        ]
    },
    "Cnda_M": {
        "description": "Change_in_Yaw_moment_due_to_aileron_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "fcs/aileron-pos-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            0.8,
            1,
            1.2,
            1.4,
            1.6
        ],
        "data": [
            0,
            0.0149,
            -0.0011,
            0.0097,
            0.0126,
            -0.004
        ]
    },
    "Cnda": {
        "description": "Yaw_moment_due_to_aileron",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "fcs/aileron-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "column": "aero/beta-rad",
        "columns": [
            -0.524,
            -0.349,
            -0.175,
            0,
            0.175,
            0.349,
            0.524
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                0.001,
                0.002,
                0.006,
                0.011,
                0.015,
                0.024,
                -0.022
            ],
            [
                0.027,
                0.014,
                0.008,
                0.011,
                0.015,
                0.01,
                -0.002
            ],
            [
                0.017,
                0.016,
                0.006,
                0.01,
                0.014,
                0.004,
                0.003
            ],
            [
                0.013,
                0.016,
                0.006,
                0.009,
                0.012,
                0.002,
                0.005
            ],
            [
                0.012,
                0.014,
                0.005,
                0.008,
                0.011,
                0.001,
                0.003
            ],
            [
                0.016,
                0.019,
                0.008,
                0.006,
                0.008,
                -0.003,
                0.001
            ],
            [
                -0.001,
                0.021,
                0.005,
                0,
                0.002,
                -0.014,
                0.009
            ],
            [
                -0.017,
                -0.002,
                -0.007,
                -0.004,
                -0.002,
                -0.006,
                0.009
            ],
            [
                -0.011,
                -0.012,
                -0.004,
                -0.007,
                -0.006,
                0.001,
                0.001
            ],
            [
                -0.017,
                -0.016,
                -0.007,
                -0.01,
                -0.012,
                -0.004,
                -0.003
            ],
            [
                -0.008,
                -0.015,
                -0.006,
                -0.004,
                -0.011,
                -0.004,
                0.002
            ],
            [
                -0.016,
                -0.011,
                -0.006,
                -0.01,
                -0.011,
                -0.006,
                -0.001
            ]
        ]
    },
    "Cndr": {
        "description": "Yaw_moment_due_to_rudder",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "fcs/rudder-pos-rad"
        ],
        "row": "aero/alpha-rad",
        "column": "aero/beta-rad",
        "columns": [
            -0.524,
            -0.349,
            -0.175,
            0,
            0.175,
            0.349,
            0.524
        ],
        "rows": [
            -0.175,
            -0.087,
            0,
            0.087,
            0.175,
            0.262,
            0.349,
            0.436,
            0.524,
            0.611,
            0.698,
            0.785
        ],
        "data": [
            [
                -0.018,
                -0.028,
                -0.037,
                -0.048,
                -0.043,
                -0.052,
                -0.062
            ],
            [
                -0.052,
                -0.051,
                -0.041,
                -0.045,
                -0.044,
                -0.034,
                -0.034
            ],
            [
                -0.052,
                -0.043,
                -0.038,
                -0.045,
                -0.041,
                -0.036,
                -0.027
            ],
            [
                -0.052,
                -0.046,
                -0.04,
                -0.045,
                -0.041,
                -0.036,
                -0.028
            ],
            [
                -0.054,
                -0.045,
                -0.04,
                -0.044,
                -0.04,
                -0.035,
                -0.027
            ],
            [
                -0.049,
                -0.049,
                -0.038,
                -0.045,
                -0.038,
                -0.028,
                -0.027
            ],
            [
                -0.059,
                -0.057,
                -0.037,
                -0.047,
                -0.034,
                -0.024,
                -0.023
            ],
            [
                -0.051,
                -0.052,
                -0.03,
                -0.048,
                -0.035,
                -0.023,
                -0.023
            ],
            [
                -0.03,
                -0.03,
                -0.027,
                -0.049,
                -0.035,
                -0.02,
                -0.019
            ],
            [
                -0.037,
                -0.033,
                -0.024,
                -0.045,
                -0.029,
                -0.016,
                -0.009
            ],
            [
                -0.026,
                -0.03,
                -0.019,
                -0.033,
                -0.022,
                -0.01,
                -0.025
            ],
            [
                -0.013,
                -0.008,
                -0.013,
                -0.016,
                -0.009,
                -0.014,
                -0.01
            ]
        ]
    },
    "Cndr_M": {
        "description": "Change_in_Yaw_moment_due_to_rudder_due_to_mach",
        "factors": [
            "aero/qbar-psf",
            "metrics/Sw-sqft",
            "metrics/bw-ft",
            "aero/alpha-rad",
            "fcs/rudder-pos-rad"
        ],
        "row": "velocities/mach",
        "rows": [
            0.6,
            1.2,
            1.6
        ],
        "data": [
            0,
            0.0401,
            0.0716
        ]
    }
};
